spring:
  application:
    name: manager-sys

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/manager_sys
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # We'll use Flyway for migrations
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 10

# RabbitMQ Queue Configuration
rabbitmq:
  queue:
    email: email.queue
  exchange:
    email: email.exchange
  routing-key:
    email: email.routing.key

  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret}
    expiration: 86400000  # 24 hours in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
      rabbitmq: INFO
    com.managersys: DEBUG

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none

# Flyway Configuration
spring.flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration
